// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjt38cTY3sqLXAiP5yXzyjD9U3b5zbqY8',
    appId: '1:22784897333:web:6c752161f5322c85595c7c',
    messagingSenderId: '22784897333',
    projectId: 'forhad-enterprise',
    authDomain: 'forhad-enterprise.firebaseapp.com',
    storageBucket: 'forhad-enterprise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAPWAwl40VFxoe02z70eFIsykUPYPefk',
    appId: '1:22784897333:android:8e83f3c5a09327a8595c7c',
    messagingSenderId: '22784897333',
    projectId: 'forhad-enterprise',
    storageBucket: 'forhad-enterprise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-NWss55WJY_zp8FYlJRykIMBZ_skW6I',
    appId: '1:22784897333:ios:c65959675ce05f26595c7c',
    messagingSenderId: '22784897333',
    projectId: 'forhad-enterprise',
    storageBucket: 'forhad-enterprise.appspot.com',
    iosClientId: '22784897333-t2mg27oslcfeb2ktmkr0kn08lthhv3pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5-NWss55WJY_zp8FYlJRykIMBZ_skW6I',
    appId: '1:22784897333:ios:7da5e3f71597c684595c7c',
    messagingSenderId: '22784897333',
    projectId: 'forhad-enterprise',
    storageBucket: 'forhad-enterprise.appspot.com',
    iosClientId: '22784897333-i8hnvn8tg883c3majhkkbkjg8c57jvo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisty.RunnerTests',
  );
}
